/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Calculadora;

/**
 *
 * @author Luan Júnior
 * @version 1.0 Beta Stark
 * @since 18/05/2017 - 00:12
 */
public class GUICalculadora extends javax.swing.JFrame {

    /**
     * Creates new form GUICalculadora
     */
    public GUICalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpt = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlNum1 = new javax.swing.JLabel();
        jlNum2 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtNum1 = new javax.swing.JTextField();
        jtNum2 = new javax.swing.JTextField();
        jrSomar = new javax.swing.JRadioButton();
        jrSubtrair = new javax.swing.JRadioButton();
        jrMultiplicar = new javax.swing.JRadioButton();
        jrDividir = new javax.swing.JRadioButton();
        jrTudo = new javax.swing.JRadioButton();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCalcular = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jlNome.setText("Nome:");

        jlNum1.setText("Primeiro Valor:");

        jlNum2.setText("Segundo Valor:");

        bgOpt.add(jrSomar);
        jrSomar.setText(" Somar");
        jrSomar.setActionCommand("Somar");

        bgOpt.add(jrSubtrair);
        jrSubtrair.setText(" Subtrair");
        jrSubtrair.setActionCommand("Subtrair");

        bgOpt.add(jrMultiplicar);
        jrMultiplicar.setText(" Multiplicar");
        jrMultiplicar.setActionCommand("multiplicar");

        bgOpt.add(jrDividir);
        jrDividir.setText(" Dividir");
        jrDividir.setActionCommand("Dividir");

        bgOpt.add(jrTudo);
        jrTudo.setText(" Tudo");
        jrTudo.setActionCommand("Tudo");

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNum1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNum2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNum1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNum2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSomar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSubtrair, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMultiplicar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrDividir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrTudo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrMultiplicar)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addComponent(jlNum1)
                            .addComponent(jlNum2))
                        .addGap(35, 35, 35)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(jtNum1)
                            .addComponent(jtNum2)))
                    .addComponent(jrSomar)
                    .addComponent(jrSubtrair)
                    .addComponent(jrDividir)
                    .addComponent(jrTudo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlNome))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNum1)
                    .addComponent(jtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNum2)
                    .addComponent(jtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jrSomar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrSubtrair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrDividir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrTudo)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        jbCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCalcularKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jbCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados)
                .addGap(23, 23, 23)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcular(){
        try{
            Calculadora calc = new Calculadora();
            calc.setNome(jtNome.getText());
            calc.setNum1(Double.parseDouble(jtNum1.getText()));
            calc.setNum2(Double.parseDouble(jtNum2.getText()));
            String opt =  bgOpt.getSelection().getActionCommand();
            
            JOptionPane.showMessageDialog(rootPane,calc.fazerCalculo(opt));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    private void limpar(){
        jtNome.setText(null);
        jtNum1.setText(null);
        jtNum2.setText(null);
        
        bgOpt.clearSelection();
        
    }
    
    
    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        calcular();
        limpar();
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
       limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCalcularKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            calcular();
            limpar();
        }
    }//GEN-LAST:event_jbCalcularKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limpar();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpt;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNum1;
    private javax.swing.JLabel jlNum2;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrDividir;
    private javax.swing.JRadioButton jrMultiplicar;
    private javax.swing.JRadioButton jrSomar;
    private javax.swing.JRadioButton jrSubtrair;
    private javax.swing.JRadioButton jrTudo;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNum1;
    private javax.swing.JTextField jtNum2;
    // End of variables declaration//GEN-END:variables
}
