/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author Aluno
 */
public class UICadCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadCadastro
     */
    
    private Cliente c = new Cliente();
    
    public UICadCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPagamento = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jlPagamento = new javax.swing.JLabel();
        jrAVista = new javax.swing.JRadioButton();
        jr1 = new javax.swing.JRadioButton();
        jr2 = new javax.swing.JRadioButton();
        jr3 = new javax.swing.JRadioButton();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jlReceber = new javax.swing.JLabel();
        jcEmail = new javax.swing.JCheckBox();
        jcCartao = new javax.swing.JCheckBox();
        jcTelefone = new javax.swing.JCheckBox();
        jcDinheiro = new javax.swing.JCheckBox();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbValores = new javax.swing.JButton();
        jlpRelatorio = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlValor.setText("Valor Total");

        jlPagamento.setText("Forma de pagamento");

        bgPagamento.add(jrAVista);
        jrAVista.setText("à vista");
        jrAVista.setActionCommand("Vista");

        bgPagamento.add(jr1);
        jr1.setText("1x");
        jr1.setActionCommand("1");

        bgPagamento.add(jr2);
        jr2.setText("2x");
        jr2.setActionCommand("2");

        bgPagamento.add(jr3);
        jr3.setText("3x");
        jr3.setActionCommand("3");

        jlEmail.setText("Email");

        jlTelefone.setText("Telefone");

        jlReceber.setText("Deseja receber");

        jcEmail.setText("Emails chatos promocionais");

        jcCartao.setText("cartões de aniversário");

        jcTelefone.setText("Telefones sobre novas promoções");

        jcDinheiro.setText("Dinheiro via correio");

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPagamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrAVista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jr2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jr3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlReceber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcCartao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcDinheiro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDadosLayout.createSequentialGroup()
                            .addComponent(jlReceber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcCartao)
                                .addComponent(jcEmail))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcTelefone)
                                .addComponent(jcDinheiro)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDadosLayout.createSequentialGroup()
                            .addComponent(jlPagamento)
                            .addGap(18, 18, 18)
                            .addComponent(jrAVista)
                            .addGap(10, 10, 10)
                            .addComponent(jr1)
                            .addGap(10, 10, 10)
                            .addComponent(jr2)
                            .addGap(18, 18, 18)
                            .addComponent(jr3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPagamento)
                    .addComponent(jrAVista)
                    .addComponent(jr1)
                    .addComponent(jr2)
                    .addComponent(jr3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlReceber)
                    .addComponent(jcEmail)
                    .addComponent(jcTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcCartao)
                    .addComponent(jcDinheiro))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbValores.setText("Valores");
        jbValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValoresActionPerformed(evt);
            }
        });

        jlpRelatorio.setText("Relatório");
        jlpRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlpRelatorioActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbValores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jlpRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar)
                .addGap(18, 18, 18)
                .addComponent(jbValores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar)
                    .addComponent(jbValores)
                    .addComponent(jlpRelatorio))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cadastrar(){
        ArrayList<String> opt = new ArrayList<>();
        c.setNome(jtNome.getText());
        try{
            c.setValorTotal(Double.parseDouble(jtValor.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Por favor digite numero no campo invés de texto");
        }
        
        c.setFormaPagamento(bgPagamento.getSelection().getActionCommand());
        c.setEmail(jtEmail.getText());
        c.setTelefone(jtTelefone.getText());
        
        if(jcCartao.isSelected()){
            opt.add(jcCartao.getText());
        }
         
        if(jcDinheiro.isSelected()){
            opt.add(jcDinheiro.getText());
        }
         
        if(jcEmail.isSelected()){
            opt.add(jcEmail.getText());
        }   
        
        if(jcTelefone.isSelected()){
            opt.add(jcTelefone.getText());
        }
        c.setReceber(opt);
        
        JOptionPane.showMessageDialog(rootPane, "Cliente cadastrado com sucesso!");
    
    }//fecha cadastrar
        
    
    private void limpar(){
        jtNome.setText(null);
        jtValor.setText(null);
        
        bgPagamento.clearSelection();
        
        jtEmail.setText(null);
        jtTelefone.setText(null);
        
        jcCartao.setSelected(false);
        jcDinheiro.setSelected(false);
        jcEmail.setSelected(false);
        jcTelefone.setSelected(false);
    }//fecha limpar
    
    private void relatorio(){
        JOptionPane.showMessageDialog(rootPane, c.toString());
    }
    
    private void calcular(){
       JOptionPane.showMessageDialog(rootPane, "O Valor total com juros é"+c.calcularFormaPagameto());
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
       limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValoresActionPerformed
        calcular();
    }//GEN-LAST:event_jbValoresActionPerformed

    private void jlpRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlpRelatorioActionPerformed
        relatorio();
    }//GEN-LAST:event_jlpRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPagamento;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbValores;
    private javax.swing.JCheckBox jcCartao;
    private javax.swing.JCheckBox jcDinheiro;
    private javax.swing.JCheckBox jcEmail;
    private javax.swing.JCheckBox jcTelefone;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPagamento;
    private javax.swing.JLabel jlReceber;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlValor;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JButton jlpRelatorio;
    private javax.swing.JRadioButton jr1;
    private javax.swing.JRadioButton jr2;
    private javax.swing.JRadioButton jr3;
    private javax.swing.JRadioButton jrAVista;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
