/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import core.Security;
import core.Validation;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import models.EnderecoVO;
import models.UsuarioVO;
import services.EnderecoServices;
import services.ServicesFactory;
import services.UsuarioServices;

/**
 *
 * @author Luan Junior
 */
public class GUICadUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GUICadUsuario
     */
    public GUICadUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpDadosPessoa = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSobreNome = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlEstadoCivil = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSobreNome = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jrMasc = new javax.swing.JRadioButton();
        jrFemi = new javax.swing.JRadioButton();
        jcomboEstadoCivil = new javax.swing.JComboBox<>();
        jlDataNascimento = new javax.swing.JLabel();
        jtDataNascimento = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jlpDadosLocalidade = new javax.swing.JLayeredPane();
        jlPais = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlCep = new javax.swing.JLabel();
        jlRua = new javax.swing.JLabel();
        jtpais = new javax.swing.JTextField();
        jcomboUF = new javax.swing.JComboBox<>();
        jtBairro = new javax.swing.JTextField();
        jtCidade = new javax.swing.JTextField();
        jtRua = new javax.swing.JTextField();
        jtCep = new javax.swing.JTextField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbVoltarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuario");
        setResizable(false);

        jlpDadosPessoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNome.setText("Nome");

        jlSobreNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlSobreNome.setText("SobreNome");

        jlEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlEmail.setText("Email");

        jlSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlSexo.setText("Sexo");

        jlEstadoCivil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlEstadoCivil.setText("Estado Cívil");

        jlSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlSenha.setText("Senha");

        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtSobreNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSobreNomeKeyPressed(evt);
            }
        });

        jtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEmailKeyPressed(evt);
            }
        });

        jpSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpSenhaKeyPressed(evt);
            }
        });

        bgSexo.add(jrMasc);
        jrMasc.setText(" Masculino");
        jrMasc.setActionCommand("Masculino");
        jrMasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMascKeyPressed(evt);
            }
        });

        bgSexo.add(jrFemi);
        jrFemi.setText(" Feminino");
        jrFemi.setActionCommand("Feminino");
        jrFemi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemiKeyPressed(evt);
            }
        });

        jcomboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um estado cívil", "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)" }));
        jcomboEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboEstadoCivilKeyPressed(evt);
            }
        });

        jlDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlDataNascimento.setText("Data de Nascimento");

        jtDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDataNascimentoKeyPressed(evt);
            }
        });

        jlTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone");

        jtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTelefoneKeyPressed(evt);
            }
        });

        jlpDadosPessoa.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlSobreNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtSobreNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jpSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jrMasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jrFemi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jcomboEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlDataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtDataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosPessoaLayout = new javax.swing.GroupLayout(jlpDadosPessoa);
        jlpDadosPessoa.setLayout(jlpDadosPessoaLayout);
        jlpDadosPessoaLayout.setHorizontalGroup(
            jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                        .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addGap(46, 46, 46)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTelefone)
                                    .addComponent(jlSexo))
                                .addGap(31, 31, 31)
                                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                        .addComponent(jrMasc)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrFemi))
                                    .addComponent(jtTelefone))))
                        .addGap(26, 26, 26)
                        .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSobreNome)
                            .addComponent(jlSenha)
                            .addComponent(jlDataNascimento)
                            .addComponent(jlEstadoCivil)))
                    .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addGap(48, 48, 48)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addComponent(jtSobreNome, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addComponent(jpSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addComponent(jcomboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jlpDadosPessoaLayout.setVerticalGroup(
            jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSobreNome)
                    .addComponent(jtSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSenha)
                    .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNascimento)
                    .addComponent(jlTelefone)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMasc)
                    .addComponent(jrFemi)
                    .addComponent(jlSexo)
                    .addComponent(jlEstadoCivil)
                    .addComponent(jcomboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jlpDadosLocalidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPais.setText("País");

        jlEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEstado.setText("Estado");

        jlCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCidade.setText("Cidade");

        jlBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBairro.setText("Bairro");

        jlCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCep.setText("Cep");

        jlRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlRua.setText("Rua");

        jtpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpaisKeyPressed(evt);
            }
        });

        jcomboUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcomboUF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboUFKeyPressed(evt);
            }
        });

        jtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtBairroKeyPressed(evt);
            }
        });

        jtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCidadeKeyPressed(evt);
            }
        });

        jtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRuaKeyPressed(evt);
            }
        });

        jtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCepKeyPressed(evt);
            }
        });

        jlpDadosLocalidade.setLayer(jlPais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlCep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtpais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jcomboUF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtCep, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLocalidadeLayout = new javax.swing.GroupLayout(jlpDadosLocalidade);
        jlpDadosLocalidade.setLayout(jlpDadosLocalidadeLayout);
        jlpDadosLocalidadeLayout.setHorizontalGroup(
            jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCidade)
                    .addComponent(jlPais)
                    .addComponent(jlRua))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jtpais, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEstado)
                    .addComponent(jlBairro)
                    .addComponent(jlCep))
                .addGap(31, 31, 31)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcomboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jtCep, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLocalidadeLayout.setVerticalGroup(
            jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRua)
                            .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCep)
                            .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                        .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtpais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPais)
                            .addComponent(jlEstado)
                            .addComponent(jcomboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlBairro)
                            .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCidade))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar Dados");
        jbLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbVoltarLogin.setText("Voltar Para o Login ->");
        jbVoltarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarLoginActionPerformed(evt);
            }
        });
        jbVoltarLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbVoltarLoginKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbVoltarLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbVoltarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbVoltarLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlpDadosPessoa)
                        .addContainerGap())
                    .addComponent(jlpDadosLocalidade)
                    .addComponent(jlpAcoes)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDadosPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpDadosLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            UsuarioVO usuario = new UsuarioVO();
           // editado.setIdUsuario(user.getIdUsuario());
            String nome1;
            String nome2;
            if(!Validation.validarNome(jtNome.getText())){
                 throw  new Exception("Erro Nome Inválido, por favor digite o nome válido!");
            }else{
                nome1 = jtNome.getText();
            }
            if(!Validation.validarNome(jtSobreNome.getText())){
                throw  new Exception("Erro SobreNome Inválido, por favor digite o sobrenome válido!");
            }else{
                nome2 = jtSobreNome.getText();
            }
            usuario.setNomeCompleto(nome1+" "+nome2);
            if(!Validation.verificarEmail(jtEmail.getText())){
                throw  new Exception("Erro email Inválido, por favor digite o email válido!");
            }else{
                UsuarioServices useremail = ServicesFactory.getUsuarioServices();
                if(useremail.verificaEmail(jtEmail.getText())){
                    throw  new Exception("Erro Já existe alguem com este email, por favor digite outro email!");
                }else{
                    usuario.setEmail(jtEmail.getText());
                }  
            }
            String senha = String.valueOf(jpSenha.getPassword());
            if(!Validation.validarSenhaSimples(senha)){
                throw  new Exception("Erro senha Inválida, por favor digite a sehha novamente!");
            }else{
                usuario.setSenha(Security.cryptografar(senha));
            }
            if(!Validation.validarTelefone(jtTelefone.getText())){
                throw  new Exception("Erro telefone Inválido, por favor digite o telefone válido!");
            }else{
                UsuarioServices usertel = ServicesFactory.getUsuarioServices();
                if(usertel.verificaTelefone(jtTelefone.getText())){
                    throw  new Exception("Erro telefone ja cadastrado em nosso sistema, por favor digite outro telefone!");
                }else{
                    usuario.setTelefone(jtTelefone.getText());
                } 
            }
            String[] data = jtDataNascimento.getText().split("/");//dd/mm/YYYY
            if(!Validation.validarData(jtDataNascimento.getText()) || jtDataNascimento.getText().equalsIgnoreCase("")){
                throw  new Exception("Erro data Inválida, por favor digite a data válida!");
            }else{
                usuario.setDataNasc(data[2]+"-"+data[1]+"-"+data[0]);
            }
           
            if(!jrMasc.isSelected() && !jrFemi.isSelected()){
                throw  new Exception("Erro Genero Inválido, por favor selecione teu genero");
            }else{
                usuario.setSexo(bgSexo.getSelection().getActionCommand());
            }
            
            if(jcomboEstadoCivil.getSelectedItem().toString().equalsIgnoreCase("Selecione um estado cívil")){
                throw  new Exception("Erro Estado Cívil Inválido, por favor selecione o estado cívil novamente!");
            }else{
                usuario.setEstadoCivil(jcomboEstadoCivil.getSelectedItem().toString());
            }
            usuario.setStatus("Online");
            
            //Lidando com os campos de Endereço
            EnderecoVO e = new EnderecoVO();
            
            //e.setUsuario(usuario);
            
            if(!Validation.verificarTexto(jtpais.getText())){
                throw  new Exception("Erro País Inválido, por favor digite um país novamente!");
            }else{
                e.setPais(jtpais.getText());
            }
            if(jcomboUF.getSelectedItem().toString().equalsIgnoreCase("Selecione um estado")){
                throw  new Exception("Erro Estado Inválido, por favor selecione o estado novamente!");
            }else{
                e.setEstado(jcomboUF.getSelectedItem().toString());
            }
            if(!Validation.verificarTexto(jtCidade.getText())){
                throw  new Exception("Erro Cidade Inválida, por favor digite uma cidade novamente!");
            }else{
                e.setCidade(jtCidade.getText());
            }
            if(!Validation.verificarTexto(jtBairro.getText())){
                throw  new Exception("Erro Bairro Inválido, por favor digite um bairro novamente!");
            }else{
                e.setBairro(jtBairro.getText());
            }
            if(!Validation.verificarTexto(jtRua.getText())){
                throw  new Exception("Erro Rua Inválida, por favor digite a rua novamente!");
            }else{
                e.setRua(jtRua.getText());
            }
            if(!Validation.validarCEP(jtCep.getText())){
                throw  new Exception("Erro CEP Inválido, por favor digite um cep novamente!");
            }else{
                e.setCep(jtCep.getText());
            }
            
             UsuarioServices guardarU = ServicesFactory.getUsuarioServices();
             guardarU.cadastrarUsuario(usuario);
             
             UsuarioVO u = guardarU.buscarUsuarioPorEmail(jtEmail.getText());
             
             e.setUsuario(u);
            
            EnderecoServices guardarE = ServicesFactory.getEnderecoServices();
            guardarE.cadastrarEndereco(e);
            
            GUIMenuPrincipal guiPrincipal = new GUIMenuPrincipal(u);
            guiPrincipal.setVisible(true);
            this.setVisible(false);
            
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),"ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//fecha cadastrar
    
    private void limparDados(){
        jtNome.setText(null);
        jtSobreNome.setText(null);
        jtEmail.setText(null);
        jpSenha.setText(null);
        jtDataNascimento.setText(null);
        jtTelefone.setText(null);
        jcomboEstadoCivil.setSelectedIndex(0);
        bgSexo.clearSelection();
        
        jtpais.setText(null);
        jcomboUF.setSelectedIndex(0);
        jtCidade.setText(null);
        jtBairro.setText(null);
        jtRua.setText(null);
        jtCep.setText(null);
        
        jtNome.grabFocus();
    }//fecha limpar dados
    
    private void abrirTelaLogin(){
        GUILogin guiLogin = new GUILogin();
        guiLogin.setVisible(true);
        this.setVisible(false);
    }
    
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparDados();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarLoginActionPerformed
        abrirTelaLogin();
    }//GEN-LAST:event_jbVoltarLoginActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limparDados();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbVoltarLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbVoltarLoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirTelaLogin();
        }
    }//GEN-LAST:event_jbVoltarLoginKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtSobreNome.grabFocus();
        }
        
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtSobreNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSobreNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtEmail.grabFocus();
        }
    }//GEN-LAST:event_jtSobreNomeKeyPressed

    private void jtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jpSenha.grabFocus();
        }
    }//GEN-LAST:event_jtEmailKeyPressed

    private void jpSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtTelefone.grabFocus();
        }
    }//GEN-LAST:event_jpSenhaKeyPressed

    private void jtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefoneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtDataNascimento.grabFocus();
        }
    }//GEN-LAST:event_jtTelefoneKeyPressed

    private void jtDataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDataNascimentoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrMasc.grabFocus();
        }
    }//GEN-LAST:event_jtDataNascimentoKeyPressed

    private void jrMascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMascKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboEstadoCivil.grabFocus();
        }
    }//GEN-LAST:event_jrMascKeyPressed

    private void jrFemiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemiKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboEstadoCivil.grabFocus();
        }
    }//GEN-LAST:event_jrFemiKeyPressed

    private void jcomboEstadoCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboEstadoCivilKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtpais.grabFocus();
        }
    }//GEN-LAST:event_jcomboEstadoCivilKeyPressed

    private void jtpaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpaisKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboUF.grabFocus();
        }
    }//GEN-LAST:event_jtpaisKeyPressed

    private void jcomboUFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboUFKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtCidade.grabFocus();
        }
    }//GEN-LAST:event_jcomboUFKeyPressed

    private void jtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtBairro.grabFocus();
        }
    }//GEN-LAST:event_jtCidadeKeyPressed

    private void jtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBairroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtRua.grabFocus();
        }
    }//GEN-LAST:event_jtBairroKeyPressed

    private void jtRuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRuaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtCep.grabFocus();
        }
    }//GEN-LAST:event_jtRuaKeyPressed

    private void jtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCepKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar();
        }
    }//GEN-LAST:event_jtCepKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbVoltarLogin;
    private javax.swing.JComboBox<String> jcomboEstadoCivil;
    private javax.swing.JComboBox<String> jcomboUF;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlDataNascimento;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlEstadoCivil;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPais;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSobreNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDadosLocalidade;
    private javax.swing.JLayeredPane jlpDadosPessoa;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JRadioButton jrFemi;
    private javax.swing.JRadioButton jrMasc;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCep;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtDataNascimento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtSobreNome;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTextField jtpais;
    // End of variables declaration//GEN-END:variables
}
