/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import core.ManipularImagem;
import models.UsuarioVO;

/**
 *
 * @author Luan Junior
 */
public class GUIDetalhePessoa extends javax.swing.JInternalFrame {
    private UsuarioVO usuario;
    /**
     * Creates new form GUIDetalhePessoa
     */
    public GUIDetalhePessoa(UsuarioVO u) {
        initComponents();
        this.usuario = u;
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlRespIdade = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlAnos = new javax.swing.JLabel();
        jlEstadoCivil = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlRespNome = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlRespEmail = new javax.swing.JLabel();
        jlRespTelefone = new javax.swing.JLabel();
        jlRespEstadoCivil = new javax.swing.JLabel();
        jlRespSexo = new javax.swing.JLabel();
        jlRespAno = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlFoto = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detalhe da Pessoa");

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlRespIdade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespIdade.setText("0");

        jlSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlSexo.setText("Sexo:");

        jlAnos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAnos.setText("anos");

        jlEstadoCivil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlEstadoCivil.setText("Estado Civil:");

        jlData.setText("Data de Nascimento");

        jlEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlEmail.setText("Email:");

        jlRespNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespNome.setText("Fulano Silva");

        jlTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlTelefone.setText("Telefone:");

        jlRespEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespEmail.setText("exemplo@exemplo.com");

        jlRespTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespTelefone.setText("5519610-2410");

        jlRespEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespEstadoCivil.setText("Solteiro(a)");

        jlRespSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespSexo.setText("Masculino");

        jlRespAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlRespAno.setText("26/01/1993");

        jlIdade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlIdade.setText("Idade:");

        jlNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlNome.setText("Nome:");

        jLayeredPane1.setLayer(jlRespIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlAnos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRespNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRespEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRespTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRespEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRespSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRespAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlRespNome))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jlRespSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jlData))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlRespTelefone)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRespEmail))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlEstadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRespEstadoCivil))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlRespAno)
                        .addGap(56, 56, 56)
                        .addComponent(jlIdade)
                        .addGap(18, 18, 18)
                        .addComponent(jlRespIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlAnos)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jlEmail)
                    .addComponent(jlRespNome)
                    .addComponent(jlRespEmail))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jlEstadoCivil)
                    .addComponent(jlRespTelefone)
                    .addComponent(jlRespEstadoCivil))
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jlIdade)
                    .addComponent(jlData)
                    .addComponent(jlRespSexo)
                    .addComponent(jlRespAno)
                    .addComponent(jlRespIdade)
                    .addComponent(jlAnos))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlFoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jlFoto)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarDados(){
        jlRespNome.setText(usuario.getNomeCompleto());
        jlRespEmail.setText(usuario.getEmail());
        jlRespTelefone.setText(usuario.getTelefone());
        jlRespEstadoCivil.setText(usuario.getEstadoCivil());
        jlRespSexo.setText(usuario.getSexo());
        String ano[] = usuario.getDataNasc().split("-");
        jlRespAno.setText(ano[2]+"/"+ano[1]+"/"+ano[0]);
        jlRespIdade.setText(String.valueOf(usuario.calcularIdade()));
        if(usuario.getFoto() == null){
            jlFoto.setText("Usuário não tem foto");
        }else{
            ManipularImagem.exibiImagemLabel(usuario.getFoto(), jlFoto);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jlAnos;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEstadoCivil;
    private javax.swing.JLabel jlFoto;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRespAno;
    private javax.swing.JLabel jlRespEmail;
    private javax.swing.JLabel jlRespEstadoCivil;
    private javax.swing.JLabel jlRespIdade;
    private javax.swing.JLabel jlRespNome;
    private javax.swing.JLabel jlRespSexo;
    private javax.swing.JLabel jlRespTelefone;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlTelefone;
    // End of variables declaration//GEN-END:variables
}
