/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import core.Validation;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import models.EnderecoVO;
import services.EnderecoServices;
import services.ServicesFactory;

/**
 *
 * @author Luan Junior
 */
public class GUIEditEndereco extends javax.swing.JInternalFrame {
    private EnderecoVO endereco = new EnderecoVO();
    /**
     * Creates new form GUIEditEndereco
     */
    public GUIEditEndereco(EnderecoVO e) {
        initComponents();
        this.endereco = e;
        popularDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDadosLocalidade = new javax.swing.JLayeredPane();
        jlPais = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlCep = new javax.swing.JLabel();
        jlRua = new javax.swing.JLabel();
        jtpais = new javax.swing.JTextField();
        jcomboUF = new javax.swing.JComboBox<>();
        jtBairro = new javax.swing.JTextField();
        jtCidade = new javax.swing.JTextField();
        jtRua = new javax.swing.JTextField();
        jtCep = new javax.swing.JTextField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbAlterar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Editar Endereço");

        jlpDadosLocalidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPais.setText("País");

        jlEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEstado.setText("Estado");

        jlCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCidade.setText("Cidade");

        jlBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBairro.setText("Bairro");

        jlCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCep.setText("Cep");

        jlRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlRua.setText("Rua");

        jtpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpaisKeyPressed(evt);
            }
        });

        jcomboUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcomboUF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboUFKeyPressed(evt);
            }
        });

        jtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtBairroKeyPressed(evt);
            }
        });

        jtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCidadeKeyPressed(evt);
            }
        });

        jtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRuaKeyPressed(evt);
            }
        });

        jtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCepKeyPressed(evt);
            }
        });

        jlpDadosLocalidade.setLayer(jlPais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlCep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jlRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtpais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jcomboUF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosLocalidade.setLayer(jtCep, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLocalidadeLayout = new javax.swing.GroupLayout(jlpDadosLocalidade);
        jlpDadosLocalidade.setLayout(jlpDadosLocalidadeLayout);
        jlpDadosLocalidadeLayout.setHorizontalGroup(
            jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCidade)
                    .addComponent(jlPais)
                    .addComponent(jlRua))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jtpais)
                    .addComponent(jtRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEstado)
                    .addComponent(jlBairro)
                    .addComponent(jlCep))
                .addGap(31, 31, 31)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcomboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBairro)
                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jlpDadosLocalidadeLayout.setVerticalGroup(
            jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtpais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlPais))
                    .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCidade)))
                    .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlCep)
                                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlEstado)
                                    .addComponent(jcomboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlBairro)
                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jlpDadosLocalidadeLayout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addGroup(jlpDadosLocalidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlRua)
                                .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAlterar.setText("Alterar Dados");
        jbAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jbCancelar.setText("Cancelar Alteração");
        jbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCancelarKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlpDadosLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jlpDadosLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popularDados(){
        jtpais.setText(endereco.getPais());
        jcomboUF.setSelectedItem(endereco.getEstado());
        jtCidade.setText(endereco.getCidade());
        jtBairro.setText(endereco.getBairro());
        jtRua.setText(endereco.getRua());
        jtCep.setText(endereco.getCep());
    }
    
    private void alterar(){
        try {
            EnderecoVO e = new EnderecoVO();
            
            e.setIdEndereco(endereco.getIdEndereco());
            if(!Validation.verificarTexto(jtpais.getText())){
                throw  new Exception("Erro País Inválido, por favor digite um país novamente!");
            }else{
                e.setPais(jtpais.getText());
            }
            if(jcomboUF.getSelectedItem().toString().equalsIgnoreCase("Selecione um estado")){
                throw  new Exception("Erro Estado Inválido, por favor selecione o estado novamente!");
            }else{
                e.setEstado(jcomboUF.getSelectedItem().toString());
            }
            if(!Validation.verificarTexto(jtCidade.getText())){
                throw  new Exception("Erro Cidade Inválida, por favor digite uma cidade novamente!");
            }else{
                e.setCidade(jtCidade.getText());
            }
            if(!Validation.verificarTexto(jtBairro.getText())){
                throw  new Exception("Erro Bairro Inválido, por favor digite um bairro novamente!");
            }else{
                e.setBairro(jtBairro.getText());
            }
            if(!Validation.verificarTexto(jtRua.getText())){
                throw  new Exception("Erro Rua Inválida, por favor digite a rua novamente!");
            }else{
                e.setRua(jtRua.getText());
            }
            if(!Validation.validarCEP(jtCep.getText())){
                throw  new Exception("Erro CEP Inválido, por favor digite um cep novamente!");
            }else{
                e.setCep(jtCep.getText());
            }
            
            EnderecoServices es = ServicesFactory.getEnderecoServices();
            es.alterarEndereco(e);
            
            JOptionPane.showMessageDialog(rootPane, "Endereço Alterado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),"ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cancelar(){
        this.dispose();
    }
    
    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            alterar();
        }
    }//GEN-LAST:event_jbAlterarKeyPressed

    private void jbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCancelarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cancelar();
        }
    }//GEN-LAST:event_jbCancelarKeyPressed

    private void jtpaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpaisKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboUF.grabFocus();
        }
    }//GEN-LAST:event_jtpaisKeyPressed

    private void jcomboUFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboUFKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtCidade.grabFocus();
        }
    }//GEN-LAST:event_jcomboUFKeyPressed

    private void jtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtBairro.grabFocus();
        }
    }//GEN-LAST:event_jtCidadeKeyPressed

    private void jtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBairroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtRua.grabFocus();
        }
    }//GEN-LAST:event_jtBairroKeyPressed

    private void jtRuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRuaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtCep.grabFocus();
        }
    }//GEN-LAST:event_jtRuaKeyPressed

    private void jtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCepKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            alterar();
        }
    }//GEN-LAST:event_jtCepKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcomboUF;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlPais;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDadosLocalidade;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCep;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtpais;
    // End of variables declaration//GEN-END:variables
}
