/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import core.Security;
import core.Validation;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.UsuarioVO;
import services.ServicesFactory;
import services.UsuarioServices;

/**
 *
 * @author Luan Junior
 */
public class GUIEditSenha extends javax.swing.JInternalFrame {
    private UsuarioVO usuario = new UsuarioVO();
    /**
     * Creates new form GUIEditSenha
     */
    public GUIEditSenha(UsuarioVO user) throws SQLException {
        initComponents();
        UsuarioServices se = ServicesFactory.getUsuarioServices();
        this.usuario = se.buscarUsuarioPorEmail(user.getEmail());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDados = new javax.swing.JLayeredPane();
        jlSenhaAntiga = new javax.swing.JLabel();
        jlSenhaNova1 = new javax.swing.JLabel();
        jlSenhaNova2 = new javax.swing.JLabel();
        jpSenhaAntiga = new javax.swing.JPasswordField();
        jpSenhaNova1 = new javax.swing.JPasswordField();
        jpSenhaNova2 = new javax.swing.JPasswordField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbTrocar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Trocar Senha de Usuário");

        jlpDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlSenhaAntiga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlSenhaAntiga.setText("Digite sua Senha Antiga");

        jlSenhaNova1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlSenhaNova1.setText("Digite sua Nova Senha");

        jlSenhaNova2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlSenhaNova2.setText("Repita sua Nova Senha");

        jlpDados.setLayer(jlSenhaAntiga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSenhaNova1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSenhaNova2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jpSenhaAntiga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jpSenhaNova1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jpSenhaNova2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSenhaAntiga)
                    .addComponent(jlSenhaNova1)
                    .addComponent(jlSenhaNova2))
                .addGap(33, 33, 33)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpSenhaAntiga)
                    .addComponent(jpSenhaNova2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jpSenhaNova1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenhaAntiga)
                    .addComponent(jpSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jlSenhaNova1))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jpSenhaNova1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpSenhaNova2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jlSenhaNova2))
                .addGap(38, 38, 38))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbTrocar.setText("Confirmar Alteração de Senha");
        jbTrocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTrocarActionPerformed(evt);
            }
        });
        jbTrocar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTrocarKeyPressed(evt);
            }
        });

        jbCancelar.setText("Cancelar Alteração");
        jbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCancelarKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbTrocar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jbTrocar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbTrocar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCampos(){
        jpSenhaAntiga.setText(null);
        jpSenhaNova1.setText(null);
        jpSenhaNova2.setText(null);
        jpSenhaAntiga.grabFocus();
    }
    
    
    private void trocarSenha(){
        try {
            
            if(!Validation.validarSenhaSimples(String.valueOf(jpSenhaAntiga.getPassword()))){
                throw new Exception("Erro Senha Inválida");
            }
            if(!Validation.validarSenhaSimples(String.valueOf(jpSenhaNova1.getPassword()))){
                throw new Exception("Erro Senha Inválida");
            }
            if(!Validation.validarSenhaSimples(String.valueOf(jpSenhaNova2.getPassword()))){
                throw new Exception("Erro Senha Inválida");
            }
            if(String.valueOf(jpSenhaNova1.getPassword()).equalsIgnoreCase(String.valueOf(jpSenhaNova2.getPassword()))){
                String senhaVelhaBD = usuario.getSenha();
                String senhaVelhaDigitada = Security.cryptografar(String.valueOf(jpSenhaAntiga.getPassword()));
                String senhaNovaDigitada = Security.cryptografar(String.valueOf(jpSenhaNova1.getPassword()));
                if(senhaVelhaDigitada.equalsIgnoreCase(senhaVelhaBD)){
                    UsuarioVO u = new UsuarioVO();
                    u.setIdUsuario(usuario.getIdUsuario());
                    u.setSenha(senhaNovaDigitada);
                    UsuarioServices us = ServicesFactory.getUsuarioServices();
                    us.alterarSenha(u);
                    
                    limparCampos();
                    JOptionPane.showMessageDialog(rootPane, "Senha Alterada com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Senha Antiga Incorreta Por favor Digite a Senha Novamente!","ERRO",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "A primeira senha e a segunda nova não coincidem Por favor digite Novamente","ERRO",JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),"ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jbTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrocarActionPerformed
        trocarSenha();
    }//GEN-LAST:event_jbTrocarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbTrocarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTrocarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            trocarSenha();
        }
    }//GEN-LAST:event_jbTrocarKeyPressed

    private void jbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCancelarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.dispose();
        }
    }//GEN-LAST:event_jbCancelarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbTrocar;
    private javax.swing.JLabel jlSenhaAntiga;
    private javax.swing.JLabel jlSenhaNova1;
    private javax.swing.JLabel jlSenhaNova2;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JPasswordField jpSenhaAntiga;
    private javax.swing.JPasswordField jpSenhaNova1;
    private javax.swing.JPasswordField jpSenhaNova2;
    // End of variables declaration//GEN-END:variables
}
