/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import core.Validation;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.UsuarioVO;
import services.ServicesFactory;
import services.UsuarioServices;

/**
 *
 * @author Luan Junior
 */
public class GUIEditarPerfil extends javax.swing.JInternalFrame {
    private UsuarioVO user = new UsuarioVO();
    /**
     * Creates new form GUIEditarPerfil
     */
    public GUIEditarPerfil(UsuarioVO userAgent) throws Exception {
        initComponents();
        this.user = userAgent;
        mostrarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDadosPessoa = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSobreNome = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlEstadoCivil = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSobreNome = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jrMasc = new javax.swing.JRadioButton();
        jrFemi = new javax.swing.JRadioButton();
        jcomboEstadoCivil = new javax.swing.JComboBox<>();
        jlDataNascimento = new javax.swing.JLabel();
        jtDataNascimento = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbAlterarPerfil = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Editar Perfil de Usuário");

        jlpDadosPessoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlNome.setText("Nome");

        jlSobreNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlSobreNome.setText("SobreNome");

        jlEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlEmail.setText("Email");

        jlSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlSexo.setText("Sexo");

        jlEstadoCivil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlEstadoCivil.setText("Estado Cívil");

        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtSobreNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSobreNomeKeyPressed(evt);
            }
        });

        jtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEmailKeyPressed(evt);
            }
        });

        jrMasc.setText(" Masculino");
        jrMasc.setActionCommand("Masculino");
        jrMasc.setEnabled(false);

        jrFemi.setText(" Feminino");
        jrFemi.setActionCommand("Feminino");
        jrFemi.setEnabled(false);

        jcomboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um estado cívil", "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)" }));
        jcomboEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboEstadoCivilKeyPressed(evt);
            }
        });

        jlDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlDataNascimento.setText("Data de Nascimento");

        jtDataNascimento.setEnabled(false);

        jlTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone");

        jtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTelefoneKeyPressed(evt);
            }
        });

        jlpDadosPessoa.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlSobreNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtSobreNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jrMasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jrFemi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jcomboEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlDataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtDataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDadosPessoa.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosPessoaLayout = new javax.swing.GroupLayout(jlpDadosPessoa);
        jlpDadosPessoa.setLayout(jlpDadosPessoaLayout);
        jlpDadosPessoaLayout.setHorizontalGroup(
            jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addGap(48, 48, 48)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jlDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                        .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addGap(46, 46, 46)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTelefone)
                                    .addComponent(jlSexo))
                                .addGap(31, 31, 31)
                                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                        .addComponent(jrMasc)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrFemi))
                                    .addComponent(jtTelefone))))
                        .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jlSobreNome))
                            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlEstadoCivil)))
                        .addGap(41, 41, 41)))
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jtSobreNome, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jcomboEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jlpDadosPessoaLayout.setVerticalGroup(
            jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosPessoaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSobreNome)
                    .addComponent(jtSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDataNascimento))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlEstadoCivil)
                        .addComponent(jcomboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlTelefone)
                        .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jlpDadosPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMasc)
                    .addComponent(jrFemi)
                    .addComponent(jlSexo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAlterarPerfil.setBackground(new java.awt.Color(0, 153, 153));
        jbAlterarPerfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAlterarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jbAlterarPerfil.setText("Editar");
        jbAlterarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAlterarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPerfilActionPerformed(evt);
            }
        });
        jbAlterarPerfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarPerfilKeyPressed(evt);
            }
        });

        jbCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar.setText("Cancelar");
        jbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCancelarKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbAlterarPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jbAlterarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDadosPessoa)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDadosPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarDados() throws Exception{
        UsuarioServices us = ServicesFactory.getUsuarioServices();
        try {
            UsuarioVO usuario = us.buscarUsuarioPorEmail(user.getEmail());
            user.setIdUsuario(usuario.getIdUsuario());
            jtEmail.setText(usuario.getEmail());
            jtTelefone.setText(usuario.getTelefone());
            
            String[] data = usuario.getDataNasc().split("-");

            jtDataNascimento.setText(data[2]+"/"+data[1]+"/"+data[0]);

            if(usuario.getSexo().equalsIgnoreCase("Masculino")){
                jrMasc.setSelected(true);
            }else{
                jrFemi.setSelected(true);
            }  
            String separarNome = usuario.getNomeCompleto();
            String nome[] = separarNome.split(" ");
            jtNome.setText(nome[0]);
            jtSobreNome.setText(nome[1]);
            
            jcomboEstadoCivil.setSelectedItem(usuario.getEstadoCivil());
            
            
        } catch (SQLException ex) {
        }
        
    }//fecha método
    
    private void editarPerfil(){
        try {
            //Validando os Dados Novamente
            UsuarioVO editado = new UsuarioVO();
            editado.setIdUsuario(user.getIdUsuario());
            String nome1;
            String nome2;
            if(!Validation.validarNome(jtNome.getText())){
                 throw  new Exception("Erro Nome Inválido, por favor digite o nome válido!");
            }else{
                nome1 = jtNome.getText();
            }
            if(!Validation.validarNome(jtSobreNome.getText())){
                throw  new Exception("Erro SobreNome Inválido, por favor digite o sobrenome válido!");
            }else{
                nome2 = jtSobreNome.getText();
            }
            editado.setNomeCompleto(nome1+" "+nome2);
            if(!Validation.verificarEmail(jtEmail.getText())){
                throw  new Exception("Erro email Inválido, por favor digite o email válido!");
            }else{
                editado.setEmail(jtEmail.getText());
            }
            if(!Validation.validarTelefone(jtTelefone.getText())){
                throw  new Exception("Erro telefone Inválido, por favor digite o telefone válido!");
            }else{
                editado.setTelefone(jtTelefone.getText());
            }
            if(jcomboEstadoCivil.getSelectedItem().toString().equalsIgnoreCase("Selecione um estado cívil")){
                throw  new Exception("Erro Estado Cívil Inválido, por favor selecione o estado cívil novamente!");
            }else{
                editado.setEstadoCivil(jcomboEstadoCivil.getSelectedItem().toString());
            }
            
            UsuarioServices us = ServicesFactory.getUsuarioServices();
            us.alterarPerfil(editado);
           
            JOptionPane.showMessageDialog(rootPane, "Perfil Alterado com sucesso!","Avio",JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e.getMessage(),"ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jbAlterarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPerfilActionPerformed
        editarPerfil();
    }//GEN-LAST:event_jbAlterarPerfilActionPerformed

    private void jbAlterarPerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarPerfilKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            editarPerfil();
        }
    }//GEN-LAST:event_jbAlterarPerfilKeyPressed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCancelarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.dispose();
        }
    }//GEN-LAST:event_jbCancelarKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtSobreNome.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtSobreNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSobreNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtEmail.grabFocus();
        }
    }//GEN-LAST:event_jtSobreNomeKeyPressed

    private void jtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtTelefone.grabFocus();
        }
    }//GEN-LAST:event_jtEmailKeyPressed

    private void jtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefoneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcomboEstadoCivil.grabFocus();
        }
    }//GEN-LAST:event_jtTelefoneKeyPressed

    private void jcomboEstadoCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboEstadoCivilKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            editarPerfil();
        }
    }//GEN-LAST:event_jcomboEstadoCivilKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterarPerfil;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcomboEstadoCivil;
    private javax.swing.JLabel jlDataNascimento;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEstadoCivil;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSobreNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDadosPessoa;
    private javax.swing.JRadioButton jrFemi;
    private javax.swing.JRadioButton jrMasc;
    private javax.swing.JTextField jtDataNascimento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSobreNome;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
