/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import core.Security;
import core.Validation;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import models.Garbage;
import models.UsuarioVO;
import server.ChatServer;
import services.ServicesFactory;
import services.UsuarioServices;

/**
 *
 * @author Luan Junior
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuLoginECad
     */
    public GUILogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTextEntrarNo = new javax.swing.JLabel();
        jlTextWindowsLive = new javax.swing.JLabel();
        jlTextMessenger = new javax.swing.JLabel();
        jlIconUser = new javax.swing.JLabel();
        jtLogin = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jlEsqueceuSenha = new javax.swing.JLabel();
        jbEntrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jlTextNovaConta = new javax.swing.JLabel();
        jlInscrevase = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlGrupo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Windows Live Messenger");
        setResizable(false);

        jlTextEntrarNo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlTextEntrarNo.setText("Entrar no");

        jlTextWindowsLive.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlTextWindowsLive.setText("Windows Live");
        jlTextWindowsLive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlTextWindowsLiveMouseClicked(evt);
            }
        });

        jlTextMessenger.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTextMessenger.setText("Messenger");

        jlIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconMessenger.png"))); // NOI18N

        jtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtLoginFocusLost(evt);
            }
        });
        jtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtLoginKeyPressed(evt);
            }
        });

        jpSenha.setText("00000");
        jpSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpSenhaFocusLost(evt);
            }
        });
        jpSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpSenhaKeyPressed(evt);
            }
        });

        jlEsqueceuSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlEsqueceuSenha.setForeground(new java.awt.Color(0, 0, 255));
        jlEsqueceuSenha.setText("Esqueceu sua senha?");
        jlEsqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbEntrar.setText("Entrar");
        jbEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        jbEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbEntrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Cancelar");
        jbLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlTextNovaConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlTextNovaConta.setText("Não possui uma conta no Messenger?");

        jlInscrevase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlInscrevase.setForeground(new java.awt.Color(0, 0, 255));
        jlInscrevase.setText("Inscreva-se");
        jlInscrevase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlInscrevase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInscrevaseMouseClicked(evt);
            }
        });

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlEmail.setText("Email");

        jlSenha.setText("Senha");

        jlGrupo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlGrupo.setText("em Grupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jlIconUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTextNovaConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlInscrevase))
                            .addComponent(jlEsqueceuSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEmail)
                                    .addComponent(jlSenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTextWindowsLive)
                                .addGap(18, 18, 18)
                                .addComponent(jlTextMessenger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlGrupo))
                            .addComponent(jlTextEntrarNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlTextEntrarNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTextWindowsLive)
                    .addComponent(jlTextMessenger)
                    .addComponent(jlGrupo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlIconUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEmail))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSenha))
                        .addGap(18, 18, 18)
                        .addComponent(jlEsqueceuSenha)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTextNovaConta)
                    .addComponent(jlInscrevase))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logar(){
        try {
            UsuarioVO user = new UsuarioVO();
            if(!Validation.verificarEmail(jtLogin.getText())){
                throw new Exception("Erro Email Inválido, por favor digite o email valido :D");
            }else{
               user.setEmail(jtLogin.getText());
            }
            if(!Validation.validarSenhaSimples(String.valueOf(jpSenha.getPassword()))){
                throw  new Exception("Erro Senha Inválida, por favor digite a senha valida!");
            }else{
                user.setSenha(Security.cryptografar(String.valueOf(jpSenha.getPassword())));
            }
            
            UsuarioServices us = ServicesFactory.getUsuarioServices();
            if(us.verificaEmail(user.getEmail())){
                if(us.logarSistema(user)){ 
                    user.setStatus("Online");      
                    us.alterarStatus(user);
                    GUIMenuPrincipal guiPrincipal = new GUIMenuPrincipal(user);
                    guiPrincipal.setVisible(true);
                    this.setVisible(false);
                    Garbage.carregarMemoria();
                    Garbage.limparMemoria();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Senha Incorreta Por Favor tente Novamente!");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Este email não existe");   
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void limparCampos(){
        jtLogin.setText(null);
        jpSenha.setText(null);
        Garbage.carregarMemoria();
        Garbage.limparMemoria();
        jtLogin.grabFocus();
    }
    
    private void abrirJanelaCadastro(){
        GUICadUsuario caduser = new GUICadUsuario();
        caduser.setVisible(true);
        this.setVisible(false);
    }
    
    
    private void jtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLoginFocusGained
       if(jtLogin.getText().equalsIgnoreCase("exemplo@gmail.com")){
           jtLogin.setText(null);
       }
    }//GEN-LAST:event_jtLoginFocusGained

    private void jpSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpSenhaFocusGained
        if(String.valueOf(jpSenha.getPassword()).equalsIgnoreCase("00000")){
           jpSenha.setText(null); 
        }
    }//GEN-LAST:event_jpSenhaFocusGained

    private void jtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLoginFocusLost
        if(jtLogin.getText().isEmpty()){
            jtLogin.setText("exemplo@gmail.com");
        }
        
    }//GEN-LAST:event_jtLoginFocusLost

    private void jpSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpSenhaFocusLost
        if(String.valueOf(jpSenha.getPassword()).isEmpty()){
            jpSenha.setText("00000");
        }
    }//GEN-LAST:event_jpSenhaFocusLost

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        logar();
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbEntrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }
    }//GEN-LAST:event_jbEntrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limparCampos();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jlInscrevaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInscrevaseMouseClicked
        abrirJanelaCadastro();
    }//GEN-LAST:event_jlInscrevaseMouseClicked

    private void jlTextWindowsLiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTextWindowsLiveMouseClicked
        if(jlTextWindowsLive.getText().equalsIgnoreCase("Windows Live")){
            jlTextWindowsLive.setText("Linux Live");
        }else if(jlTextWindowsLive.getText().equalsIgnoreCase("Linux Live")){
            jlTextWindowsLive.setText("Windows Live");
        }
        
    }//GEN-LAST:event_jlTextWindowsLiveMouseClicked

    private void jtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jpSenha.grabFocus();
        }
    }//GEN-LAST:event_jtLoginKeyPressed

    private void jpSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }
    }//GEN-LAST:event_jpSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbEntrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEsqueceuSenha;
    private javax.swing.JLabel jlGrupo;
    private javax.swing.JLabel jlIconUser;
    private javax.swing.JLabel jlInscrevase;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTextEntrarNo;
    private javax.swing.JLabel jlTextMessenger;
    private javax.swing.JLabel jlTextNovaConta;
    private javax.swing.JLabel jlTextWindowsLive;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtLogin;
    // End of variables declaration//GEN-END:variables
}
