/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author Luan Júnior
 * @version 1.0 Beta
 * @since 22/05/2017
 */
public class UICadCliente extends javax.swing.JFrame {

    /**
     * Creates new form UICadCliente
     */
    
    private Cliente c = new Cliente();
    
    public UICadCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgOpcao = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlpossuiCartao = new javax.swing.JLabel();
        jlQtde = new javax.swing.JLabel();
        jlQual = new javax.swing.JLabel();
        jlConta = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jrSim = new javax.swing.JRadioButton();
        jrNao = new javax.swing.JRadioButton();
        jsQtde = new javax.swing.JSpinner();
        jlpQual = new javax.swing.JLayeredPane();
        jcbVisa = new javax.swing.JCheckBox();
        jcbElo = new javax.swing.JCheckBox();
        jcbBanriCompras = new javax.swing.JCheckBox();
        jcbMaster = new javax.swing.JCheckBox();
        jcbHiper = new javax.swing.JCheckBox();
        jcbAmerican = new javax.swing.JCheckBox();
        jlpConta = new javax.swing.JLayeredPane();
        jcbItau = new javax.swing.JCheckBox();
        jcbBradesco = new javax.swing.JCheckBox();
        jcbBanriSul = new javax.swing.JCheckBox();
        jcbSantander = new javax.swing.JCheckBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlSexo.setText("Sexo");

        jlpossuiCartao.setText("Possui Cartão?");

        jlQtde.setText("Quantos?");

        jlQual.setText("Qual(is)");

        jlConta.setText("Conta(s)");

        bgSexo.add(jrMasculino);
        jrMasculino.setText(" masculino");
        jrMasculino.setActionCommand("Masculino");

        bgSexo.add(jrFeminino);
        jrFeminino.setText(" feminino");
        jrFeminino.setActionCommand("Feminino");

        bgOpcao.add(jrSim);
        jrSim.setText(" sim");
        jrSim.setActionCommand("Sim");

        bgOpcao.add(jrNao);
        jrNao.setText(" não");
        jrNao.setActionCommand("Não");

        jlpQual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcbVisa.setText(" Visa");

        jcbElo.setText(" Elo");

        jcbBanriCompras.setText(" BanriCompras");

        jcbMaster.setText(" MasterCard");

        jcbHiper.setText(" HiperCard");

        jcbAmerican.setText(" American Express");

        jlpQual.setLayer(jcbVisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQual.setLayer(jcbElo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQual.setLayer(jcbBanriCompras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQual.setLayer(jcbMaster, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQual.setLayer(jcbHiper, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQual.setLayer(jcbAmerican, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpQualLayout = new javax.swing.GroupLayout(jlpQual);
        jlpQual.setLayout(jlpQualLayout);
        jlpQualLayout.setHorizontalGroup(
            jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpQualLayout.createSequentialGroup()
                .addGroup(jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbVisa)
                    .addComponent(jcbMaster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbElo)
                    .addComponent(jcbHiper))
                .addGap(20, 20, 20)
                .addGroup(jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbAmerican)
                    .addComponent(jcbBanriCompras))
                .addGap(22, 22, 22))
        );
        jlpQualLayout.setVerticalGroup(
            jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpQualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbVisa)
                    .addComponent(jcbElo)
                    .addComponent(jcbBanriCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addGroup(jlpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMaster)
                    .addComponent(jcbHiper)
                    .addComponent(jcbAmerican)))
        );

        jlpConta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcbItau.setText(" Itaú");

        jcbBradesco.setText(" Bradesco");

        jcbBanriSul.setText(" Banrisul");

        jcbSantander.setText(" Santander");

        jlpConta.setLayer(jcbItau, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpConta.setLayer(jcbBradesco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpConta.setLayer(jcbBanriSul, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpConta.setLayer(jcbSantander, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpContaLayout = new javax.swing.GroupLayout(jlpConta);
        jlpConta.setLayout(jlpContaLayout);
        jlpContaLayout.setHorizontalGroup(
            jlpContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbItau)
                    .addComponent(jcbBanriSul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbBradesco)
                    .addComponent(jcbSantander))
                .addGap(71, 71, 71))
        );
        jlpContaLayout.setVerticalGroup(
            jlpContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbItau)
                    .addComponent(jcbBradesco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addGroup(jlpContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBanriSul)
                    .addComponent(jcbSantander)))
        );

        jLayeredPane1.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlpossuiCartao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlQtde, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlQual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrSim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrNao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jsQtde, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlpQual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlpConta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addComponent(jlSexo)
                            .addComponent(jlpossuiCartao)
                            .addComponent(jlQtde))
                        .addGap(24, 24, 24)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrMasculino)
                                        .addComponent(jrSim))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jsQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrNao)
                                    .addComponent(jrFeminino)))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlQual)
                            .addComponent(jlConta))
                        .addGap(24, 24, 24)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlpQual)
                            .addComponent(jlpConta))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSexo)
                            .addComponent(jrMasculino)
                            .addComponent(jrFeminino))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlpossuiCartao)
                            .addComponent(jrSim)
                            .addComponent(jrNao))
                        .addGap(25, 25, 25)
                        .addComponent(jlQtde))
                    .addComponent(jsQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlQual)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlConta)
                        .addGap(40, 40, 40))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlpConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jLayeredPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbRelatorio.setText("Relatório");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });
        jbRelatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbRelatorioKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        ArrayList<String> contas = new ArrayList<>();
        ArrayList<String> cartao = new ArrayList<>();
        
        c.setNome(jtNome.getText());
        c.setSexo(bgSexo.getSelection().getActionCommand());
        c.setVerificaCartao(bgOpcao.getSelection().getActionCommand());
        
        c.setQtde(Integer.parseInt(jsQtde.getValue().toString()));
        if(jcbVisa.isSelected()){
            cartao.add(jcbVisa.getText());
        }
        if(jcbElo.isSelected()){
            cartao.add(jcbElo.getText());
        }
        if(jcbBanriCompras.isSelected()){
            cartao.add(jcbBanriCompras.getText());
        }
        if(jcbMaster.isSelected()){
            cartao.add(jcbMaster.getText());
        }
        if(jcbHiper.isSelected()){
            cartao.add(jcbHiper.getText());
        }
        if(jcbAmerican.isSelected()){
            cartao.add(jcbAmerican.getText());
        }
        
        c.setNomeCartao(cartao);
        
       if(jcbItau.isSelected()){
            contas.add(jcbItau.getText());
        } 
       if(jcbBradesco.isSelected()){
            contas.add(jcbBradesco.getText());
        } 
       if(jcbBanriSul.isSelected()){
            contas.add(jcbBanriSul.getText());
        } 
       if(jcbSantander.isSelected()){
            contas.add(jcbSantander.getText());
        } 
       
       c.setContas(contas);
       
       JOptionPane.showMessageDialog(rootPane, "Dados cadastrados com sucesso!");
        
    }
    
    private void limpar(){
        jtNome.setText(null);
        bgSexo.clearSelection();
        bgOpcao.clearSelection();
        
        jsQtde.setValue(0);
        
        jcbVisa.setSelected(false);
        jcbElo.setSelected(false);
        jcbBanriCompras.setSelected(false);
        jcbMaster.setSelected(false);
        jcbHiper.setSelected(false);
        jcbAmerican.setSelected(false);
        
        jcbItau.setSelected(false);
        jcbBradesco.setSelected(false);
        jcbBanriSul.setSelected(false);
        jcbSantander.setSelected(false);
    }
    
    private void relatorio(){
        
        JOptionPane.showMessageDialog(rootPane, "Dados "+c.toString(), "Dados do cliente", JOptionPane.PLAIN_MESSAGE);
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        relatorio();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar();
            limpar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limpar();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbRelatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbRelatorioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            relatorio();
        }
    }//GEN-LAST:event_jbRelatorioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcao;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JCheckBox jcbAmerican;
    private javax.swing.JCheckBox jcbBanriCompras;
    private javax.swing.JCheckBox jcbBanriSul;
    private javax.swing.JCheckBox jcbBradesco;
    private javax.swing.JCheckBox jcbElo;
    private javax.swing.JCheckBox jcbHiper;
    private javax.swing.JCheckBox jcbItau;
    private javax.swing.JCheckBox jcbMaster;
    private javax.swing.JCheckBox jcbSantander;
    private javax.swing.JCheckBox jcbVisa;
    private javax.swing.JLabel jlConta;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlQtde;
    private javax.swing.JLabel jlQual;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLayeredPane jlpConta;
    private javax.swing.JLayeredPane jlpQual;
    private javax.swing.JLabel jlpossuiCartao;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JRadioButton jrNao;
    private javax.swing.JRadioButton jrSim;
    private javax.swing.JSpinner jsQtde;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
